"""Reference distribution of the estimator's own ratio outputs.

A phrase like "broad shoulders" is meaningless without a population to be broad
relative to, and the right population here is not textbook anthropometry — it is
the distribution of what *this estimator produces*. The two differ systematically:
shoulder breadth is read a little below the acromion, leg length from the hip
joint rather than the crotch. Scoring against anatomical percentiles would call
an ordinary body narrow-shouldered and short-legged, which is exactly what it did
before this table existed.

So this is a calibration artefact, not a fact about human bodies. It is
regenerated by ``scripts/calibrate_ratios.py``, and **it must be regenerated**
whenever the estimator changes or when the service is deployed against a
population unlike the one it was fitted on. The values below were fitted on the
synthetic population in :mod:`arcbody.training.synthetic`, which makes them a
starting point rather than a claim about real people.

Contrast with :data:`arcbody.measure.schema.RATIO_BOUNDS`, which is a much wider
plausibility guard answering a different question: "is this a body at all, or a
failed segmentation?"
"""

from __future__ import annotations

from typing import Final

#: ``ratio -> (p10, p50, p90)`` of the estimator's output on the reference set.
REFERENCE_PERCENTILES: Final[dict[str, tuple[float, float, float]]] = {
    "shoulder_to_stature": (0.192, 0.2236, 0.2512),
    "chest_to_stature": (0.1692, 0.1919, 0.2092),
    "waist_to_stature": (0.1181, 0.1513, 0.1838),
    "hip_to_stature": (0.1611, 0.1931, 0.2201),
    "thigh_to_stature": (0.0773, 0.0901, 0.1031),
    "upper_arm_to_stature": (0.0457, 0.0563, 0.0686),
    "neck_to_stature": (0.0577, 0.0665, 0.0744),
    "torso_to_stature": (0.3356, 0.3612, 0.3905),
    "leg_to_stature": (0.4039, 0.433, 0.4533),
    "arm_to_stature": (0.3501, 0.3655, 0.473),
    "waist_to_hip": (0.7031, 0.7922, 0.8824),
    "shoulder_to_waist": (1.2, 1.4559, 1.8551),
    "shoulder_to_hip": (1.0, 1.1613, 1.3611),
    "chest_to_waist": (1.0525, 1.2517, 1.5687),
}

#: Fitted on this many synthetic subjects; see ``scripts/calibrate_ratios.py``.
REFERENCE_SAMPLE_SIZE: Final[int] = 300

#: Band edges in percentile space. Five bands: the outer two are worth saying
#: out loud, the middle one is "average" and deliberately says nothing.
_BAND_EDGES: Final[tuple[float, ...]] = (0.15, 0.35, 0.65, 0.85)


def percentile_of(name: str, value: float) -> float | None:
    """Where ``value`` sits in the reference distribution, in ``[0, 1]``.

    Piecewise-linear through the three known quantiles, and linearly extrapolated
    beyond them with the same local slope so that an extreme body still ranks
    monotonically instead of saturating at the edge.
    """
    reference = REFERENCE_PERCENTILES.get(name)
    if reference is None:
        return None
    p10, p50, p90 = reference
    if p90 <= p10:
        return None
    if value <= p50:
        span = max(p50 - p10, 1e-9)
        return float(max(0.0, 0.5 - 0.4 * (p50 - value) / span))
    span = max(p90 - p50, 1e-9)
    return float(min(1.0, 0.5 + 0.4 * (value - p50) / span))


def band_of(name: str, value: float) -> int | None:
    """Which of five descriptor bands a ratio falls in, 0 lowest."""
    percentile = percentile_of(name, value)
    if percentile is None:
        return None
    band = 0
    for edge in _BAND_EDGES:
        if percentile >= edge:
            band += 1
    return band
